### ISSUE TITLE
Recognize All Contributors with allcontributors.org bot

### ISSUE THREAD

**Issue by NicolasStr** [TypeCobolTeam/typecobolteam.github.io#25]
This is common in new open-source web projects.
Contributors will be added in README.md file with emoji keys, dependants on if they contributed to translation or else ..

This is working with a bot, which has accesses only to specific repository with these permissions:
- Write access to code
- Read access to metadata
- Read and write access to issues and pull requests

This works as automation with basic Natural Language Parsing and recognizes the intents. If not, we can specify a type of contribution on any PR/Issue by adding `@all-contributors please add <username> for <contributions>`

More informations:
https://allcontributors.org/docs/en/bot/usage

@smedilol, do you think we could use it ?

**Comment by smedilol** [comment]
No sorry, because of Write access to code
