### ISSUE TITLE
Add CI/CD

### ISSUE THREAD

**Issue by NicolasStr** [TypeCobolTeam/typecobolteam.github.io#4]
### Let's add some CI with travis-ci (_I suppose we should use this tool because of easiness_)

Goal of this CI is:

- Run tests on all branches when PR is sent

- Build the gatsby build and push it to master once we validate a merge on a specific branch.
The problems is the following: We can't merge into master because this is the branch where the content of our build will locate, so we need to create a new branch like "to-master" or use develop as a "master"-alternative.

@TypeCobolTeam/newcomer **Please tell me what you think about it, I think creating a new branch is the best idea, but I don't know how we should name it.**

**Comment by smedilol** [comment]
Here's what we currently do:
Run CI on a branch each time a commit is pushed on it.
For PR, AppVeyor will first clone the target branch of the PR (usually develop) and the merge the branch of the PR on it (it's a local merge) then run CI on this local branch.


I'd prefer to use the same process for all our repositories:
So use master branch to tag stuff ready to be realeased.
Use develop branch which contains stuff for the next release.
When you work on an issue, create a branch that starts with the ID of the issue.

**Comment by smedilol** [comment]
See :
https://github.com/TypeCobolTeam/TypeCobol/wiki/BranchingModel

**Comment by smedilol** [comment]
Of to test Travis, but first we need to check which permissions are needed.
If Travis ask for a full repo access this will not be possible due to our security constraint.

**Comment by smedilol** [comment]
After discussion, we have to use master branch to publish web site.
So let's use:

- **master** to publish
- **develop** for the content of the next release
- **releases** to tag version

When we release, we 
- merge develop to releases
- tag releases
- merge to master

**Comment by NicolasStr** [comment]
Ok so finally, we're going to use the corporate azure devops @ EI.

We just need to create a pipeline definition in a YAML file `azure-pipelines.yml`

PR to follow

**Comment by NicolasStr** [comment]
PR #13 is a first try for CI/CD on Azure Devops @ EI.

**Comment by NicolasStr** [comment]
Update: We will work on CI/CD at end of dev when we will be ready release the site.

**Comment by NicolasStr** [comment]
CI/CD is in a WIP current state. I am working in Netlify's integration with tests.

**Comment by NicolasStr** [comment]
It's done and it's working!
